const ImageActionTypes = {
    FACE_RECOGNITION_START: 'FACE_RECOGNITION_START',
    FACE_RECOGNITION_SUCCESS: 'FACE_RECOGNITION_SUCCESS',
    FACE_RECOGNITION_FAILURE: 'FACE_RECOGNITION_FAILURE',
    UPDATE_IMAGE_SOURCE: 'UPDATE_IMAGE_SOURCE',
    CALCULATE_FACE_LOCATION: 'CALCULATE_FACE_LOCATION',
    CALCULATE_IMAGE_SIZE: 'CALCULATE_IMAGE_SIZE',
    RESET_IMAGE_STATE: 'RESET_IMAGE_STATE',
}

export default ImageActionTypes