const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    SIGN_OUT: 'SIGN_OUT',

    UPDATE_PEOPLE_DETECTED_START: 'UPDATE_PEOPLE_DETECTED_START',
    UPDATE_PEOPLE_DETECTED_SUCCESS: 'UPDATE_PEOPLE_DETECTED_SUCCESS',
    UPDATE_PEOPLE_DETECTED_FAILURE: 'UPDATE_PEOPLE_DETECTED_FAILURE',
}

export default UserActionTypes